apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: aibrix
    app.kubernetes.io/managed-by: kustomize
  name: system
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all
  namespace: aibrix-system
spec:
  podSelector: {}
  ingress:
  - {} 
  egress:
  - {}
  policyTypes:
  - Ingress
  - Egress